import Head from 'next/head';
// import Image from 'next/image';
import { useRouter } from 'next/router';

import { UserProfileCarousel } from '#/special';

// import styles from '@/styles/Home.module.css';
import userData from './userprofile/userData.json';

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Study PR</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UserProfileCarousel router={router} users={userData} />
    </>
  );
}
